[package]
name = "A-"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
rand = "0.8.5"
[dependencies.sdl2]
features = ["bundled", "image"]
version = "0.36.0"